#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "There needs to be a bucket name. e.g. my-bucket-name"
    exit 1
fi
if [ -z "$2" ]; then
    echo "There needs to be a key. e.g. my-file-name"
    exit 1
fi
bucket=$1
key=$2

aws s3api delete-object \
--bucket "$bucket" \
--key "$key"
