tasks:
  - name: utils
    # 'before' runs before 'init' and 'command', ideal for early setup like modifying environment variables.
    # 'init' runs once when the workspace is created, perfect for one-time setup like installing packages.
    # 'command' runs every time the workspace starts, used to finalize setup like sourcing environment variables.
    before: |
      echo 'export PATH=$PATH:/workspace/aws-examples/bin' >> ~/.bashrc
    init: |
      sudo apt-get install -y tree
    command: |
      source ~/.bashrc

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      git config --global credential.helper store && \
      git remote set-url origin https://davidpangsw:$GITHUB_TOKEN@github.com/davidpangsw/aws-examples.git

      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
